### ISSUE TITLE
New error in version 1.0.5: window is not defined

### ISSUE THREAD

**Issue by jchappell82** [Cretezy/braintree-web-drop-in-react#15]
When attempting to start up my dev server for a React app (on React 15.6.2) using version 1.0.5 of the drop-in, a `ReferenceError: window is not defined` is thrown on startup.  This did not occur prior to the upgrades to the babel libraries used today.  Sanitized log is below.  

Upon examining the library code from npm, the `window` use appears at character 2601 of the module.  Perhaps something changed in the babel configuration that is causing this?  The major side-effect of the issue is that it prevents use in an app that allows for server side rendering.

```/Users/jon/Code/may/poppins/node_modules/braintree-web-drop-in-react/dist/index.js:1
(function (exports, require, module, __filename, __dirname) { !function(e,r){"object"==typeof exports&&"object"==typeof module?module.exports=r(require("@babel/runtime-corejs2/helpers/interopRequireDefault"),require("@babel/runtime-corejs2/regenerator"),require("@babel/runtime-corejs2/helpers/objectSpread"),require("@babel/runtime-corejs2/helpers/asyncToGenerator"),require("@babel/runtime-corejs2/helpers/classCallCheck"),require("@babel/runtime-corejs2/helpers/createClass"),require("@babel/runtime-corejs2/helpers/possibleConstructorReturn"),require("@babel/runtime-corejs2/helpers/getPrototypeOf"),require("@babel/runtime-corejs2/helpers/inherits"),require("@babel/runtime-corejs2/helpers/assertThisInitialized"),require("@babel/runtime-corejs2/helpers/defineProperty")):"function"==typeof define&&define.amd?define(["@babel/runtime-corejs2/helpers/interopRequireDefault","@babel/runtime-corejs2/regenerator","@babel/runtime-corejs

ReferenceError: window is not defined
    at Object.<anonymous> (/path/to/project/node_modules/braintree-web-drop-in-react/dist/index.js:1:2601)
    at Module._compile (module.js:652:30)
    at Module._extensions..js (module.js:663:10)
    at Object.require.extensions.(anonymous function) [as .js] (/path/to/project/node_modules/babel-register/lib/node.js:152:7)
    at Module.load (module.js:565:32)
    at tryModuleLoad (module.js:505:12)
    at Function.Module._load (module.js:497:3)
    at Module.require (module.js:596:17)
    at require (internal/module.js:11:18)
    at Object.<anonymous> (/path/to/project/lib/components/Checkout/Payment/Payment.js:23:32)
    at Module._compile (module.js:652:30)
    at loader (/path/to/project/node_modules/babel-register/lib/node.js:144:5)
    at Object.require.extensions.(anonymous function) [as .js] (/path/to/project/node_modules/babel-register/lib/node.js:154:7)
    at Module.load (module.js:565:32)
    at tryModuleLoad (module.js:505:12)
    at Function.Module._load (module.js:497:3)
```

**Comment by jchappell82** [comment]
I should note, you can replicate this issue with a minimum project that does nothing but `require` the module, followed by running it via `node app.js`

**Comment by conciousweb** [comment]
@jchappell82 did you find a solution to this issue?

**Comment by Cretezy** [comment]
Hey! I thought I had replied to this.

Can you give me a full code example? It seems like you are running the code in Node and not in the browser, where `window` would obviously not be present.

**Comment by pantharshit00** [comment]
Having same issue in SSR. Any updates?

**Comment by pantharshit00** [comment]
No, the problem is the way you guys are bundling this. I copied and pasted the index.js in my app and it works like a charm. It is broken in 1.0.5 not 1.0.4 

Consider roll-up for bundling this

**Comment by pho3nixf1re** [comment]
A release needs to be pushed to npm for this to be fixed. The PR was merged mid-October...
